---
- name: jenkins slave setup using ansible
  hosts: jenkins-slave
  become: true
  tasks: 
    - name: yum install java 17
      yum: 
        name: java-17-amazon-corretto
        state: present
    - name: install maven 
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
    - name: extract maven pkg
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
        remote_src: yes
